name: Sync Files
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@gh-pages
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_LABELS: |
            file-sync
            automerge
          ASSIGNEES: jonnyborbs